#!/usr/bin/env fish

if set -q argv[1];
	set light $argv[1]
else
	set light 255
end

if test $light -eq 0
	nix-shell -p hueadm --run "hueadm light Arbeitszimmer off"
else 
	nix-shell -p hueadm --run "hueadm light Arbeitszimmer \=$light"
end

nix-shell -p hueadm --run 'hueadm group Bedroom off'
