#!/usr/bin/env fish

if set -q argv[1];
	set light $argv[1]
else
	set light 255
end

if test $light -eq 0
	hueadm light Arbeitszimmer off
else 
	hueadm light Arbeitszimmer \=$light
end

hueadm group Bedroom off
